// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BannerDocumentDataSlicesSlice = never;

/**
 * Content for Banner documents
 */
interface BannerDocumentData {
  /**
   * Título field in *Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Subtítulo field in *Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.subtitulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * Texto field in *Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.texto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texto: prismic.KeyTextField;

  /**
   * Label_CTA field in *Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.label_cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_cta: prismic.KeyTextField;

  /**
   * Video field in *Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video: prismic.KeyTextField;

  /**
   * Slice Zone field in *Banner*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BannerDocumentDataSlicesSlice> /**
   * Meta Description field in *Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: banner.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Banner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: banner.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Banner document from Prismic
 *
 * - **API ID**: `banner`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BannerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BannerDocumentData>, "banner", Lang>;

type BlogDocumentDataSlicesSlice =
  | NewsletterSlice
  | CasesSliceSlice
  | RecentsPostsAndCategoriesSlice;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<BlogDocumentData>, "blog", Lang>;

type BlogPostDocumentDataSlicesSlice =
  | NewsletterSlice
  | BlogImageSliceSlice
  | BlogParagraphSliceSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Date field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Autor field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.autor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  autor: prismic.KeyTextField;

  /**
   * Time of reading (m) field in *Blog Post*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.time_of_reading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  time_of_reading: prismic.NumberField;

  /**
   * category field in *Blog Post*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"category">;

  /**
   * Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

/**
 * Content for Category documents
 */
interface CategoryDocumentData {
  /**
   * Name field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Is visible field in *Category*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: category.is_visible
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_visible: prismic.BooleanField;
}

/**
 * Category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

/**
 * Item in *FAQ → item*
 */
export interface FaqDocumentDataItemItem {
  /**
   * pergunta field in *FAQ → item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.item[].pergunta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pergunta: prismic.KeyTextField;

  /**
   * resposta field in *FAQ → item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.item[].resposta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta: prismic.KeyTextField;

  /**
   * topico field in *FAQ → item*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.item[].topico
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  topico: prismic.ContentRelationshipField<"category">;
}

type FaqDocumentDataSlicesSlice = never;

/**
 * Content for FAQ documents
 */
interface FaqDocumentData {
  /**
   * Banner Texto field in *FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.banner_texto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  banner_texto: prismic.KeyTextField;

  /**
   * item field in *FAQ*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.item[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  item: prismic.GroupField<Simplify<FaqDocumentDataItemItem>>;

  /**
   * Slice Zone field in *FAQ*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FaqDocumentDataSlicesSlice> /**
   * Meta Description field in *FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: faq.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *FAQ*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: faq.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * FAQ document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FaqDocumentData>, "faq", Lang>;

/**
 * Item in *Footer → Links Navegação*
 */
export interface FooterDocumentDataLinksItem {
  /**
   * Label field in *Footer → Links Navegação*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Footer → Links Navegação*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

/**
 * Item in *Footer → Labels Contato*
 */
export interface FooterDocumentDataLabelsContatoItem {
  /**
   * label field in *Footer → Labels Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.labels_contato[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Footer → Botões Contato*
 */
export interface FooterDocumentDataBotoesContatoItem {
  /**
   * Icone field in *Footer → Botões Contato*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.botoes_contato[].icone
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icone: prismic.ImageField<never>;

  /**
   * Link field in *Footer → Botões Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.botoes_contato[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

/**
 * Item in *Footer → Redes Sociais*
 */
export interface FooterDocumentDataRedesSociaisItem {
  /**
   * Icone field in *Footer → Redes Sociais*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.redes_sociais[].icone
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icone: prismic.ImageField<never>;

  /**
   * Link field in *Footer → Redes Sociais*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.redes_sociais[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

type FooterDocumentDataSlicesSlice = never;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Descrição Logo field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.descricao_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_logo: prismic.KeyTextField;

  /**
   * CTA Label field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Subtítulo Navegação field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.subtitulo_navegacao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo_navegacao: prismic.KeyTextField;

  /**
   * Links Navegação field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<FooterDocumentDataLinksItem>>;

  /**
   * Subtítulo Contato field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.subtitulo_contato
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo_contato: prismic.KeyTextField;

  /**
   * Labels Contato field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.labels_contato[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  labels_contato: prismic.GroupField<
    Simplify<FooterDocumentDataLabelsContatoItem>
  >;

  /**
   * Botões Contato field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.botoes_contato[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  botoes_contato: prismic.GroupField<
    Simplify<FooterDocumentDataBotoesContatoItem>
  >;

  /**
   * Subtítulo Newsletter field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.subtitulo_newsletter
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo_newsletter: prismic.KeyTextField;

  /**
   * Descrição Newsletter field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.descricao_newsletter
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_newsletter: prismic.KeyTextField;

  /**
   * Direitos field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.direitos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  direitos: prismic.KeyTextField;

  /**
   * Endereço field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.endereco
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  endereco: prismic.KeyTextField;

  /**
   * Redes Sociais field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.redes_sociais[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  redes_sociais: prismic.GroupField<
    Simplify<FooterDocumentDataRedesSociaisItem>
  >;

  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice> /**
   * Meta Description field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: footer.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: footer.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;

/**
 * Item in *Header → Links*
 */
export interface HeaderDocumentDataLinksItem {
  /**
   * Label field in *Header → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Header → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.links[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

type HeaderDocumentDataSlicesSlice = never;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Logo Mobile field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo_mobile
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_mobile: prismic.ImageField<never>;

  /**
   * Logo Menu Aberto field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo_menu_aberto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_menu_aberto: prismic.ImageField<never>;

  /**
   * Links field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<HeaderDocumentDataLinksItem>>;

  /**
   * Label CTA field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.label_cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_cta: prismic.KeyTextField;

  /**
   * Label Entrar field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.label_entrar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_entrar: prismic.KeyTextField;

  /**
   * Slice Zone field in *Header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HeaderDocumentData>, "header", Lang>;

type LandingPageDocumentDataSlicesSlice =
  | RecentPostsSlice
  | BigNumbersSliceSlice
  | PartnersSliceSlice
  | ContatoSlice
  | CasesSliceSlice
  | FeaturesSliceSlice;

/**
 * Content for Landing Page documents
 */
interface LandingPageDocumentData {
  /**
   * Slice Zone field in *Landing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

/**
 * Item in *Postagens destacadas → Posts*
 */
export interface PostagensDestacadasDocumentDataPostsItem {
  /**
   * Post a ser destacado: field in *Postagens destacadas → Posts*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: postagens_destacadas.posts[].data
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  data: prismic.ContentRelationshipField<"blog_post">;
}

/**
 * Content for Postagens destacadas documents
 */
interface PostagensDestacadasDocumentData {
  /**
   * Posts field in *Postagens destacadas*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: postagens_destacadas.posts[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  posts: prismic.GroupField<Simplify<PostagensDestacadasDocumentDataPostsItem>>;
}

/**
 * Postagens destacadas document from Prismic
 *
 * - **API ID**: `postagens_destacadas`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostagensDestacadasDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PostagensDestacadasDocumentData>,
    "postagens_destacadas",
    Lang
  >;

export type AllDocumentTypes =
  | BannerDocument
  | BlogDocument
  | BlogPostDocument
  | CategoryDocument
  | FaqDocument
  | FooterDocument
  | HeaderDocument
  | LandingPageDocument
  | PostagensDestacadasDocument;

/**
 * Primary content in *BigNumbersSlice → Primary*
 */
export interface BigNumbersSliceSliceDefaultPrimary {
  /**
   * BigNumbersTitle field in *BigNumbersSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: big_numbers_slice.primary.bignumberstitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bignumberstitle: prismic.KeyTextField;

  /**
   * BigNumbersTitleHighlights field in *BigNumbersSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Palavras para destacar
   * - **API ID Path**: big_numbers_slice.primary.bignumberstitlehighlights
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bignumberstitlehighlights: prismic.KeyTextField;

  /**
   * BigNumbersSliceButtontext field in *BigNumbersSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: big_numbers_slice.primary.bignumbersslicebuttontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bignumbersslicebuttontext: prismic.KeyTextField;

  /**
   * BigNumbersSliceButtonLink field in *BigNumbersSlice → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: big_numbers_slice.primary.bignumbersslicebuttonlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  bignumbersslicebuttonlink: prismic.LinkField;

  /**
   * BigNumbersImage field in *BigNumbersSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: big_numbers_slice.primary.bignumbersimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bignumbersimage: prismic.ImageField<never>;

  /**
   * BigNumbersImageVisibility field in *BigNumbersSlice → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: big_numbers_slice.primary.bignumbersimagevisibility
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bignumbersimagevisibility: prismic.BooleanField;
}

/**
 * Primary content in *BigNumbersSlice → Items*
 */
export interface BigNumbersSliceSliceDefaultItem {
  /**
   * BigNumberSliceTriggerTitle field in *BigNumbersSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: big_numbers_slice.items[].bignumberslicetriggertitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bignumberslicetriggertitle: prismic.KeyTextField;

  /**
   * BigNumberSliceTriggerNumber field in *BigNumbersSlice → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: big_numbers_slice.items[].bignumberslicetriggernumber
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  bignumberslicetriggernumber: prismic.NumberField;

  /**
   * BigNumberSliceTriggerNumberFraction field in *BigNumbersSlice → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: big_numbers_slice.items[].bignumberslicetriggernumberfraction
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bignumberslicetriggernumberfraction: prismic.BooleanField;
}

/**
 * Default variation for BigNumbersSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigNumbersSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BigNumbersSliceSliceDefaultPrimary>,
  Simplify<BigNumbersSliceSliceDefaultItem>
>;

/**
 * Slice variation for *BigNumbersSlice*
 */
type BigNumbersSliceSliceVariation = BigNumbersSliceSliceDefault;

/**
 * BigNumbersSlice Shared Slice
 *
 * - **API ID**: `big_numbers_slice`
 * - **Description**: BigNumbersSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigNumbersSliceSlice = prismic.SharedSlice<
  "big_numbers_slice",
  BigNumbersSliceSliceVariation
>;

/**
 * Primary content in *BlogImageSlice → Primary*
 */
export interface BlogImageSliceSliceDefaultPrimary {
  /**
   * image field in *BlogImageSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_image_slice.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Legenda field in *BlogImageSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_image_slice.primary.legenda
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  legenda: prismic.KeyTextField;
}

/**
 * Default variation for BlogImageSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogImageSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogImageSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogImageSlice*
 */
type BlogImageSliceSliceVariation = BlogImageSliceSliceDefault;

/**
 * BlogImageSlice Shared Slice
 *
 * - **API ID**: `blog_image_slice`
 * - **Description**: BlogImageSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogImageSliceSlice = prismic.SharedSlice<
  "blog_image_slice",
  BlogImageSliceSliceVariation
>;

/**
 * Primary content in *BlogParagraphSlice → Primary*
 */
export interface BlogParagraphSliceSliceDefaultPrimary {
  /**
   * Paragraph field in *BlogParagraphSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_paragraph_slice.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;
}

/**
 * Default variation for BlogParagraphSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogParagraphSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogParagraphSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogParagraphSlice*
 */
type BlogParagraphSliceSliceVariation = BlogParagraphSliceSliceDefault;

/**
 * BlogParagraphSlice Shared Slice
 *
 * - **API ID**: `blog_paragraph_slice`
 * - **Description**: BlogParagraphSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogParagraphSliceSlice = prismic.SharedSlice<
  "blog_paragraph_slice",
  BlogParagraphSliceSliceVariation
>;

/**
 * Primary content in *CasesSlice → Primary*
 */
export interface CasesSliceSliceDefaultPrimary {
  /**
   * Title field in *CasesSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *CasesSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Auto Scroll Interval (s) field in *CasesSlice → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 10
   * - **API ID Path**: cases_slice.primary.auto_scroll_interval
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  auto_scroll_interval: prismic.NumberField;
}

/**
 * Primary content in *CasesSlice → Items*
 */
export interface CasesSliceSliceDefaultItem {
  /**
   * Image field in *CasesSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *CasesSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *CasesSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Client field in *CasesSlice → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: cases_slice.items[].client
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  client: prismic.BooleanField;

  /**
   * LeftIconText field in *CasesSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].lefticontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  lefticontext: prismic.KeyTextField;

  /**
   * RigthIcon field in *CasesSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].rigthicon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  rigthicon: prismic.ImageField<never>;

  /**
   * RigthIconText field in *CasesSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].rigthicontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  rigthicontext: prismic.KeyTextField;

  /**
   * LeftIcon field in *CasesSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].lefticon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  lefticon: prismic.ImageField<never>;
}

/**
 * CarouselLanding variation for CasesSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CasesSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CasesSliceSliceDefaultPrimary>,
  Simplify<CasesSliceSliceDefaultItem>
>;

/**
 * Primary content in *CasesSlice → Primary*
 */
export interface CasesSliceSliceBlogCarouselPrimary {
  /**
   * Auto Scroll Interval (s) field in *CasesSlice → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 10
   * - **API ID Path**: cases_slice.primary.auto_scroll_interval
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  auto_scroll_interval: prismic.NumberField;
}

/**
 * Primary content in *CasesSlice → Items*
 */
export interface CasesSliceSliceBlogCarouselItem {
  /**
   * Image field in *CasesSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *CasesSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *CasesSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * LerMaisButton field in *CasesSlice → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].lermaisbutton
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lermaisbutton: prismic.LinkField;

  /**
   * ButtonText field in *CasesSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].buttontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttontext: prismic.KeyTextField;
}

/**
 * BlogCarousel variation for CasesSlice Slice
 *
 * - **API ID**: `blogCarousel`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CasesSliceSliceBlogCarousel = prismic.SharedSliceVariation<
  "blogCarousel",
  Simplify<CasesSliceSliceBlogCarouselPrimary>,
  Simplify<CasesSliceSliceBlogCarouselItem>
>;

/**
 * Primary content in *CasesSlice → Primary*
 */
export interface CasesSliceSliceNewsSectionPrimary {
  /**
   * Title field in *CasesSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *CasesSlice → Items*
 */
export interface CasesSliceSliceNewsSectionItem {
  /**
   * Image field in *CasesSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *CasesSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *CasesSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Client field in *CasesSlice → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: cases_slice.items[].client
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  client: prismic.BooleanField;

  /**
   * LeftIconText field in *CasesSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].lefticontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  lefticontext: prismic.KeyTextField;

  /**
   * RigthIcon field in *CasesSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].rigthicon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  rigthicon: prismic.ImageField<never>;

  /**
   * RigthIconText field in *CasesSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].rigthicontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  rigthicontext: prismic.KeyTextField;

  /**
   * LeftIcon field in *CasesSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_slice.items[].lefticon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  lefticon: prismic.ImageField<never>;
}

/**
 * NewsSection variation for CasesSlice Slice
 *
 * - **API ID**: `newsSection`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CasesSliceSliceNewsSection = prismic.SharedSliceVariation<
  "newsSection",
  Simplify<CasesSliceSliceNewsSectionPrimary>,
  Simplify<CasesSliceSliceNewsSectionItem>
>;

/**
 * Slice variation for *CasesSlice*
 */
type CasesSliceSliceVariation =
  | CasesSliceSliceDefault
  | CasesSliceSliceBlogCarousel
  | CasesSliceSliceNewsSection;

/**
 * CasesSlice Shared Slice
 *
 * - **API ID**: `cases_slice`
 * - **Description**: CasesSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CasesSliceSlice = prismic.SharedSlice<
  "cases_slice",
  CasesSliceSliceVariation
>;

/**
 * Primary content in *ContatoSlice → Primary*
 */
export interface ContatoSliceDefaultPrimary {
  /**
   * Titulo field in *ContatoSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Destaque do Titulo field in *ContatoSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.primary.destaque_titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  destaque_titulo: prismic.KeyTextField;

  /**
   * Descrição field in *ContatoSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.primary.descricao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao: prismic.KeyTextField;

  /**
   * Logo Whatsapp field in *ContatoSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.primary.logo_whatsapp
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_whatsapp: prismic.ImageField<never>;

  /**
   * Link Whatsapp field in *ContatoSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.primary.link_whatsapp
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_whatsapp: prismic.KeyTextField;

  /**
   * Logo Email field in *ContatoSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.primary.logo_email
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_email: prismic.ImageField<never>;

  /**
   * Link Email field in *ContatoSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.primary.link_email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_email: prismic.KeyTextField;
}

/**
 * Default variation for ContatoSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContatoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContatoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContatoSlice*
 */
type ContatoSliceVariation = ContatoSliceDefault;

/**
 * ContatoSlice Shared Slice
 *
 * - **API ID**: `contato`
 * - **Description**: Contato
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContatoSlice = prismic.SharedSlice<
  "contato",
  ContatoSliceVariation
>;

/**
 * Primary content in *FeaturesSlice → Primary*
 */
export interface FeaturesSliceSliceDefaultPrimary {
  /**
   * Main Title field in *FeaturesSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_slice.primary.main_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  main_title: prismic.KeyTextField;

  /**
   * Right text field in *FeaturesSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_slice.primary.right_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  right_text: prismic.KeyTextField;
}

/**
 * Primary content in *FeaturesSlice → Items*
 */
export interface FeaturesSliceSliceDefaultItem {
  /**
   * Icon field in *FeaturesSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features_slice.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * CardTitle field in *FeaturesSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_slice.items[].card_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_title: prismic.KeyTextField;

  /**
   * Content field in *FeaturesSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_slice.items[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Default variation for FeaturesSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesSliceSliceDefaultPrimary>,
  Simplify<FeaturesSliceSliceDefaultItem>
>;

/**
 * Slice variation for *FeaturesSlice*
 */
type FeaturesSliceSliceVariation = FeaturesSliceSliceDefault;

/**
 * FeaturesSlice Shared Slice
 *
 * - **API ID**: `features_slice`
 * - **Description**: FeaturesSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceSlice = prismic.SharedSlice<
  "features_slice",
  FeaturesSliceSliceVariation
>;

/**
 * Primary content in *NewsletterSlice → Primary*
 */
export interface NewsletterSliceDefaultPrimary {
  /**
   * Titulo field in *NewsletterSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Subtitulo field in *NewsletterSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * Tipo field in *NewsletterSlice → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: newsletter.primary.tipo
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  tipo: prismic.BooleanField;
}

/**
 * Default variation for NewsletterSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsletterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewsletterSlice*
 */
type NewsletterSliceVariation = NewsletterSliceDefault;

/**
 * NewsletterSlice Shared Slice
 *
 * - **API ID**: `newsletter`
 * - **Description**: Newsletter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSlice = prismic.SharedSlice<
  "newsletter",
  NewsletterSliceVariation
>;

/**
 * Primary content in *PartnersSlice → Primary*
 */
export interface PartnersSliceSliceDefaultPrimary {
  /**
   * Title field in *PartnersSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *PartnersSlice → Items*
 */
export interface PartnersSliceSliceDefaultItem {
  /**
   * Logo field in *PartnersSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_slice.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for PartnersSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnersSliceSliceDefaultPrimary>,
  Simplify<PartnersSliceSliceDefaultItem>
>;

/**
 * Slice variation for *PartnersSlice*
 */
type PartnersSliceSliceVariation = PartnersSliceSliceDefault;

/**
 * PartnersSlice Shared Slice
 *
 * - **API ID**: `partners_slice`
 * - **Description**: PartnersSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersSliceSlice = prismic.SharedSlice<
  "partners_slice",
  PartnersSliceSliceVariation
>;

/**
 * Primary content in *RecentPosts → Primary*
 */
export interface RecentPostsSliceDefaultPrimary {
  /**
   * Main Title field in *RecentPosts → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recent_posts.primary.main_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  main_title: prismic.KeyTextField;

  /**
   * Call To Action Text field in *RecentPosts → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recent_posts.primary.call_to_action_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  call_to_action_text: prismic.KeyTextField;
}

/**
 * Default variation for RecentPosts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecentPostsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RecentPostsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RecentPosts*
 */
type RecentPostsSliceVariation = RecentPostsSliceDefault;

/**
 * RecentPosts Shared Slice
 *
 * - **API ID**: `recent_posts`
 * - **Description**: RecentPosts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecentPostsSlice = prismic.SharedSlice<
  "recent_posts",
  RecentPostsSliceVariation
>;

/**
 * Primary content in *RecentsPostsAndCategories → Primary*
 */
export interface RecentsPostsAndCategoriesSliceDefaultPrimary {
  /**
   * Main TItle field in *RecentsPostsAndCategories → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recents_posts_and_categories.primary.main_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  main_title: prismic.KeyTextField;

  /**
   * See all text field in *RecentsPostsAndCategories → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recents_posts_and_categories.primary.see_all_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  see_all_text: prismic.KeyTextField;
}

/**
 * Default variation for RecentsPostsAndCategories Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecentsPostsAndCategoriesSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<RecentsPostsAndCategoriesSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *RecentsPostsAndCategories*
 */
type RecentsPostsAndCategoriesSliceVariation =
  RecentsPostsAndCategoriesSliceDefault;

/**
 * RecentsPostsAndCategories Shared Slice
 *
 * - **API ID**: `recents_posts_and_categories`
 * - **Description**: RecentsPostsAndCategories
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecentsPostsAndCategoriesSlice = prismic.SharedSlice<
  "recents_posts_and_categories",
  RecentsPostsAndCategoriesSliceVariation
>;

/**
 * Default variation for Teste Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TesteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Teste*
 */
type TesteSliceVariation = TesteSliceDefault;

/**
 * Teste Shared Slice
 *
 * - **API ID**: `teste`
 * - **Description**: Teste
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TesteSlice = prismic.SharedSlice<"teste", TesteSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BannerDocument,
      BannerDocumentData,
      BannerDocumentDataSlicesSlice,
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      CategoryDocument,
      CategoryDocumentData,
      FaqDocument,
      FaqDocumentData,
      FaqDocumentDataItemItem,
      FaqDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataLinksItem,
      FooterDocumentDataLabelsContatoItem,
      FooterDocumentDataBotoesContatoItem,
      FooterDocumentDataRedesSociaisItem,
      FooterDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataLinksItem,
      HeaderDocumentDataSlicesSlice,
      LandingPageDocument,
      LandingPageDocumentData,
      LandingPageDocumentDataSlicesSlice,
      PostagensDestacadasDocument,
      PostagensDestacadasDocumentData,
      PostagensDestacadasDocumentDataPostsItem,
      AllDocumentTypes,
      BigNumbersSliceSlice,
      BigNumbersSliceSliceDefaultPrimary,
      BigNumbersSliceSliceDefaultItem,
      BigNumbersSliceSliceVariation,
      BigNumbersSliceSliceDefault,
      BlogImageSliceSlice,
      BlogImageSliceSliceDefaultPrimary,
      BlogImageSliceSliceVariation,
      BlogImageSliceSliceDefault,
      BlogParagraphSliceSlice,
      BlogParagraphSliceSliceDefaultPrimary,
      BlogParagraphSliceSliceVariation,
      BlogParagraphSliceSliceDefault,
      CasesSliceSlice,
      CasesSliceSliceDefaultPrimary,
      CasesSliceSliceDefaultItem,
      CasesSliceSliceBlogCarouselPrimary,
      CasesSliceSliceBlogCarouselItem,
      CasesSliceSliceNewsSectionPrimary,
      CasesSliceSliceNewsSectionItem,
      CasesSliceSliceVariation,
      CasesSliceSliceDefault,
      CasesSliceSliceBlogCarousel,
      CasesSliceSliceNewsSection,
      ContatoSlice,
      ContatoSliceDefaultPrimary,
      ContatoSliceVariation,
      ContatoSliceDefault,
      FeaturesSliceSlice,
      FeaturesSliceSliceDefaultPrimary,
      FeaturesSliceSliceDefaultItem,
      FeaturesSliceSliceVariation,
      FeaturesSliceSliceDefault,
      NewsletterSlice,
      NewsletterSliceDefaultPrimary,
      NewsletterSliceVariation,
      NewsletterSliceDefault,
      PartnersSliceSlice,
      PartnersSliceSliceDefaultPrimary,
      PartnersSliceSliceDefaultItem,
      PartnersSliceSliceVariation,
      PartnersSliceSliceDefault,
      RecentPostsSlice,
      RecentPostsSliceDefaultPrimary,
      RecentPostsSliceVariation,
      RecentPostsSliceDefault,
      RecentsPostsAndCategoriesSlice,
      RecentsPostsAndCategoriesSliceDefaultPrimary,
      RecentsPostsAndCategoriesSliceVariation,
      RecentsPostsAndCategoriesSliceDefault,
      TesteSlice,
      TesteSliceVariation,
      TesteSliceDefault,
    };
  }
}
