// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  features_slice: dynamic(() => import("./FeaturesSlice")),
  teste: dynamic(() => import("./Teste")),
};
