// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cases_slice: dynamic(() => import("./CasesSlice")),
  contato: dynamic(() => import("./ContatoSlice")),
  features_slice: dynamic(() => import("./FeaturesSlice")),
  partners_slice: dynamic(() => import("./PartnersSlice")),
  teste: dynamic(() => import("./Teste")),
};
