// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  big_numbers_slice: dynamic(() => import("./BigNumbersSlice")),
  cases_slice: dynamic(() => import("./CasesSlice")),
  contato: dynamic(() => import("./ContatoSlice")),
  features_slice: dynamic(() => import("./FeaturesSlice")),
  partners_slice: dynamic(() => import("./PartnersSlice")),
  recents_posts_and_categories: dynamic(
    () => import("./RecentsPostsAndCategories"),
  ),
  teste: dynamic(() => import("./Teste")),
};
