name: Unified End-to-End Tests
run-name: Was triggerd by ${{ github.actor }} 

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
  pull_request:
    branches:
      - dev
      - main
      - hmg

env:
  INDHUGE_LOCAL_URL: http://localhost:3000
  INDHUGE_PROD_URL: https://indhuge.com

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: 
          - local
          - production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
       
      - name: Cache project dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Start server (if applicable)
        run: npm start  

      - name: Run Cypress tests (prod)
        uses: cypress-io/github-action@v6.6.1
        if: ${{ github.ref_name == 'main' }}
        with:
          command: npx cypress run --config baseUrl=${{ env.INDHUGE_PROD_URL }}
        
      - name: Run Cypress tests (local)
        uses: cypress-io/github-action@v6.6.1
        if: ${{ github.ref_name != 'main' }}
        with:
          command: npx cypress run --config baseUrl=${{ env.INDHUGE_LOCAL_URL }}


      # - name: Upload test results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: cypress-test-results-${{ matrix.environment }}
      #     path: cypress/results/**/*.xml
      #     retention-days: 7
          