name: End-to-end tests
on: 
  workflow_dispatch: 
  push: 
    branches: 
      - feature/*
      - bugfix/*
      - hotfix/*
  pull_request:
    branches:
      - dev
      - hmg

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Chache test
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Cypress run
        uses: cypress-io/github-action@v6.6.1
        with:
          build: npm run build
          start: npm start
          command: npm test
