name: End-to-end tests
on: [push, workflow_dispatch, pull_request] 
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cypress run
        uses: cypress-io/github-action@v6.6.1
        with:
          start: npm run ci:serve
          command: npm test