name: End-to-End Tests

on:
  workflow_dispatch: 
  deployment_status: 
  push:
  pull_request:
    branches:
      - dev
      - hmg
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Cache project dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

  cypress-run:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    needs: build
    steps:
        
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6.6.1
        with:
          command: npx cypress run --config baseUrl=${{  github.event.deployment_status.environment_url  }}